/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './**/*.{ts,tsx}',
    '!./api/**',
    '!./node_modules/**',
  ],
  theme: {
    extend: {
      fontFamily: {
        label: ['"Space Mono"', 'monospace'],
        display: ['"Playfair Display"', 'serif'],
      },
      colors: {
        'th-bg': 'rgb(var(--color-bg) / <alpha-value>)',
        'th-bg2': 'rgb(var(--color-bg2) / <alpha-value>)',
        'th-bg3': 'rgb(var(--color-bg3) / <alpha-value>)',
        'th-text': 'rgb(var(--color-text) / <alpha-value>)',
        'th-text2': 'rgb(var(--color-text2) / <alpha-value>)',
        'th-text3': 'rgb(var(--color-text3) / <alpha-value>)',
        'th-surface': 'rgb(var(--color-surface) / <alpha-value>)',
        'th-nav-bg': 'rgb(var(--color-nav-bg) / <alpha-value>)',
        'th-nav-text': 'rgb(var(--color-nav-text) / <alpha-value>)',
        // Paper/light theme palette
        paper: '#faf6ef',
        'paper-warm': '#f5efe3',
        'paper-dark': '#ede4d3',
        'paper-darker': '#e0d3bc',
        cream: '#fefcf8',
        ink: '#2a2016',
        'ink-mid': '#4a3f30',
        'ink-soft': '#8a7f70',
        'burnt-peach': '#dd6e42',
        'blue-slate': '#4f6d7a',
        'pearl-beige': '#f0e6d0',
        'pale-sky': '#c0d6df',
        divider: '#e0d3bc',
        // Sellr palette
        'sellr-blue': '#2C4A6E',
        'sellr-amber': '#E8A838',
        'sellr-bg': '#F5F0E8',
        'sellr-charcoal': '#1A1A2E',
        'sellr-sage': '#6B8F71',
        'sellr-blue-light': '#3D6494',
        'sellr-amber-light': '#F0C060',
        'sellr-surface': '#EDE8DF',
        // Stakkd — Burgundy & Blush
        'sk-bg':            '#0E080A',
        'sk-surface':       '#1A0A10',
        'sk-surface-hover': '#200D14',
        'sk-accent':        '#8B3252',
        'sk-accent-hover':  '#6A2540',
        'sk-blush':         '#D4899A',
        'sk-deep':          '#4A1020',
        'sk-text':          '#FAF0F2',
        'sk-text2':         '#9C7A82',
        'sk-muted':         '#7A5A64',
      },
    },
  },
  plugins: [],
};
