import { Router, type Request, type Response } from 'express';
import { createClient } from '@supabase/supabase-js';
import { getStripe, getSellrWebhookSecret } from '../lib/stripe.js';
import type Stripe from 'stripe';
import { sendPaymentConfirmedEmail, sendAdminOrderAlert } from '../sellrEmails.js';
import { purchaseSlots, TIER_SLOTS } from '../sellrSlots.js';
import { requireSupabaseAdmin } from '../lib/supabaseAdmin.js';
import { errorResponse } from '../utils/errorResponse.js';

const router = Router();

const VALID_TIERS = ['starter', 'standard', 'full'] as const;
type Tier = (typeof VALID_TIERS)[number];

const TIER_AMOUNT_CENTS: Record<Tier, number> = {
  starter: 499,
  standard: 1499,
  full: 2999,
};

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

// ── POST /api/sellr/checkout/create-intent ───────────────────────────
// Creates a Stripe PaymentIntent for a Sellr order.
router.post('/api/sellr/checkout/create-intent', async (req: Request, res: Response) => {
  try {
    const { session_id, email } = req.body ?? {};

    if (!session_id || typeof session_id !== 'string') {
      errorResponse(res, 400, 'Missing or invalid session_id');
      return;
    }

    if (!email || typeof email !== 'string' || !EMAIL_RE.test(email)) {
      errorResponse(res, 400, 'Missing or invalid email');
      return;
    }

    const supabase = requireSupabaseAdmin();

    // Validate session exists, is active, and has a tier
    const { data: session, error: sessionErr } = await supabase
      .from('sellr_sessions')
      .select('id, status, expires_at, tier, record_count')
      .eq('id', session_id)
      .single();

    if (sessionErr || !session) {
      errorResponse(res, 404, 'Session not found');
      return;
    }

    if (session.status !== 'active') {
      errorResponse(res, 400, 'Session is not active');
      return;
    }

    if (new Date(session.expires_at) < new Date()) {
      errorResponse(res, 400, 'Session has expired');
      return;
    }

    if (!session.tier || !VALID_TIERS.includes(session.tier as Tier)) {
      errorResponse(res, 400, 'Session does not have a valid tier set');
      return;
    }

    const tier = session.tier as Tier;
    const amount_cents = TIER_AMOUNT_CENTS[tier];

    // Create Stripe PaymentIntent
    const stripe = await getStripe();
    const paymentIntent = await stripe.paymentIntents.create({
      amount: amount_cents,
      currency: 'usd',
      payment_method_types: ['card'],
      metadata: {
        session_id,
        tier,
        record_count: String(session.record_count ?? 0),
        sellr: 'true',
      },
    });

    // Insert sellr_order row (report_token generated by Supabase default)
    const { data: order, error: orderErr } = await supabase
      .from('sellr_orders')
      .insert({
        status: 'pending',
        session_id,
        email,
        tier,
        amount_cents,
        stripe_payment_intent: paymentIntent.id,
      })
      .select('id')
      .single();

    if (orderErr || !order) {
      console.error('[sellr-checkout] Failed to create order:', orderErr?.message);
      errorResponse(res, 500, 'Failed to create order');
      return;
    }

    res.status(201).json({
      client_secret: paymentIntent.client_secret,
      order_id: order.id,
      amount_cents,
      tier,
    });
  } catch (err) {
    console.error('[sellr-checkout] POST /create-intent error:', (err as Error).message);
    errorResponse(res, 500, 'Internal server error');
  }
});

// ── POST /api/sellr/checkout/webhook ─────────────────────────────────
// Stripe webhook handler for Sellr payment events.
// This route expects raw body — mounted with express.raw() in server/index.ts.
router.post('/api/sellr/checkout/webhook', async (req: Request, res: Response) => {
  const sig = req.headers['stripe-signature'];
  if (!sig) {
    res.status(400).json({ error: 'Missing stripe-signature header' });
    return;
  }

  const sellrWebhookSecret = await getSellrWebhookSecret();
  if (!sellrWebhookSecret) {
    console.error('[sellr-checkout] Sellr webhook secret not configured');
    res.status(500).json({ error: 'Webhook secret not configured' });
    return;
  }

  const stripe = await getStripe();

  let event: Stripe.Event;
  try {
    event = stripe.webhooks.constructEvent(req.body, sig, sellrWebhookSecret);
  } catch (err) {
    console.error('[sellr-checkout] Webhook signature verification failed:', err);
    res.status(400).json({ error: 'Invalid signature' });
    return;
  }

  console.log(`[sellr-checkout] Webhook received: ${event.type} (${event.id})`);

  const supabase = requireSupabaseAdmin();

  try {
    switch (event.type) {
      case 'payment_intent.succeeded': {
        const paymentIntent = event.data.object as Stripe.PaymentIntent;

        // Only handle Sellr payments
        if (paymentIntent.metadata?.sellr !== 'true') break;

        const { data: order, error: orderErr } = await supabase
          .from('sellr_orders')
          .select('id, report_token')
          .eq('stripe_payment_intent', paymentIntent.id)
          .single();

        if (orderErr || !order) {
          console.error('[sellr-checkout] Order not found for PI:', paymentIntent.id);
          break;
        }

        // Update order status to complete
        await supabase
          .from('sellr_orders')
          .update({ status: 'complete' })
          .eq('id', order.id);

        // Update session status to paid
        const sessionId = paymentIntent.metadata.session_id;
        if (sessionId) {
          await supabase
            .from('sellr_sessions')
            .update({ status: 'paid' })
            .eq('id', sessionId);
        }

        // ── Provision slots for the user ──────────────────────────
        if (sessionId) {
          const { data: sessionRow } = await supabase
            .from('sellr_sessions')
            .select('user_id')
            .eq('id', sessionId)
            .single();

          if (sessionRow?.user_id) {
            const tier = paymentIntent.metadata.tier;
            const slotsToAdd = TIER_SLOTS[tier] ?? 25;
            const success = await purchaseSlots(sessionRow.user_id, slotsToAdd, tier);
            if (!success) {
              console.warn(`[sellr-checkout] Failed to provision ${slotsToAdd} slots for user ${sessionRow.user_id} (tier: ${tier}). Order ${order.id} is complete — correct manually via admin tools.`);
            }
          } else {
            console.warn(`[sellr-checkout] No user_id on session ${sessionId} — skipping slot provisioning for order ${order.id}`);
          }
        }

        // ── Trigger emails (fire-and-forget) ──────────────────────
        (async () => {
          try {
            // Fetch full order row for email data
            const { data: fullOrder } = await supabase
              .from('sellr_orders')
              .select('id, email, tier, amount_cents, report_token, session_id')
              .eq('id', order.id)
              .single();

            if (!fullOrder?.email) return;

            // Fetch session for record_count + total_median
            const { data: session } = await supabase
              .from('sellr_sessions')
              .select('record_count')
              .eq('id', sessionId)
              .single();

            // Compute total_median from records
            const { data: records } = await supabase
              .from('sellr_records')
              .select('artist, title, price_median')
              .eq('session_id', sessionId)
              .order('price_median', { ascending: false });

            const allRecords = records ?? [];
            const total_median = allRecords.reduce((sum, r) => sum + (Number(r.price_median) || 0), 0);
            const top_records = allRecords.slice(0, 3).map(r => ({
              artist: r.artist,
              title: r.title,
              price_median: Number(r.price_median) || 0,
            }));

            // Payment confirmed email to customer
            sendPaymentConfirmedEmail({
              email: fullOrder.email,
              session_id: sessionId!,
              report_token: fullOrder.report_token,
              record_count: session?.record_count ?? allRecords.length,
              total_median,
              top_records,
            }).catch(err => console.error('[sellr-checkout] Payment email failed:', err));

            // Admin order alert
            sendAdminOrderAlert({
              order_id: fullOrder.id,
              email: fullOrder.email,
              tier: fullOrder.tier,
              record_count: session?.record_count ?? allRecords.length,
              amount_cents: fullOrder.amount_cents,
              total_median,
            }).catch(err => console.error('[sellr-checkout] Admin alert failed:', err));
          } catch (err) {
            console.error('[sellr-checkout] Email trigger error:', err);
          }
        })();

        break;
      }

      case 'payment_intent.payment_failed': {
        const paymentIntent = event.data.object as Stripe.PaymentIntent;

        // Only handle Sellr payments
        if (paymentIntent.metadata?.sellr !== 'true') break;

        await supabase
          .from('sellr_orders')
          .update({ status: 'failed' })
          .eq('stripe_payment_intent', paymentIntent.id);

        console.log(`[sellr-checkout] Payment failed for PI: ${paymentIntent.id}`);
        break;
      }

      default:
        console.log(`[sellr-checkout] Unhandled event type: ${event.type}`);
    }

    res.status(200).json({ received: true });
  } catch (err) {
    console.error(`[sellr-checkout] Webhook handler error for ${event.type}:`, err);
    res.status(200).json({ received: true });
  }
});

export default router;
